name: "Coverage Summary for simplecov's SimpleFormatter"
description: "Comments a pull request with code coverage"
author: "GY Noh"
branding:
  icon: "check-square"
  color: "green"
inputs:
  github-token:
    description: "Github token"
    required: true
  coverage:
    description: "Content of coverage/.last_run.json"
    required: true
runs:
  using: "node12"
  main: "index.js"
